# -----------------------Deployment---------------------- #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy-deploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: erp_proxy:v0.1
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        ports: 
        - containerPort: 80
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime

---

# -----------------------  Service  --------------------- #
apiVersion: v1
kind: Service
metadata:
  name: proxy-svc
spec:
  type: NodePort
  selector:
    app: proxy
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31100
    targetPort: 80 
