# -----------------------Deployment---------------------- #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: register-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: register
    spec:
      containers:
      - name: register
        image: erp_register:v0.1
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        ports: 
        - containerPort: 80
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime

---

# -----------------------  Service  --------------------- #
apiVersion: v1
kind: Service
metadata:
  name: register-svc
spec:
  type: NodePort
  selector:
    app: register
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31105
    targetPort: 80 
