# -----------------------Deployment---------------------- #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: usermgt-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: usermgt
    spec:
      containers:
      - name: usermgt
        image: erp_usermgt:v0.6
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
---

# -----------------------  Service  --------------------- #
apiVersion: v1
kind: Service
metadata:
  name: usermgt-svc
spec:
  type: NodePort
  selector:
    app: usermgt
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31041
    targetPort: 80 
