kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zipkin-logistics-engine-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      pv: zipkin-logistics-engine-pv

