# -----------------------Deployment---------------------- #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
      release: proc
  template:
    metadata:
      labels:
        app: customer
        release: proc
    spec:
      containers:
      - name: customer
        image: c7jdk8:v8 
        ports: 
        - containerPort: 8080
#        - containerPort: 9999
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        - name: jar-dirs
          mountPath: /usr/local/erp
        - name: zipkin-log
          mountPath: /var/log/zipkin
#        - name: xxl-job
#          mountPath: /var/log/xxl-job
        command: ["java"]
        args: ["-Duser.timezone=GMT+08","-jar","/usr/local/erp/erp_customer.jar","--spring.profiles.active=prod"]
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1"
            ephemeral-storage: "1024Mi"
          limits:
            memory: "16Gi"
            cpu: "4"
            ephemeral-storage: "10240Mi"
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      - name: jar-dirs
        hostPath:
          path: /data/gfs_data
      - name: zipkin-log
        persistentVolumeClaim:
          claimName: zipkin-customer-pvc
#      - name: xxl-job
#        nfs:
#          server: 192.168.1.252
#          path: /nfs
---

# -----------------------  Service  --------------------- #
apiVersion: v1
kind: Service
metadata:
  name: customer-svc
spec:
  type: NodePort
  selector:
    app: customer
    release: proc
  ports:
  - name: api1
    protocol: TCP
    port: 8080
    nodePort: 31071
    targetPort: 8080 
#  - name: api2
#    protocol: TCP
#    port: 9999
#    nodePort: 31999
#    targetPort: 9999 
