# -----------------------Deployment---------------------- #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logistics-engine-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logistics-engine
      release: proc
  template:
    metadata:
      labels:
        app: logistics-engine
        release: proc
    spec:
      containers:
      - name: logistics-engine
        image: c7jdk8:v8 
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        - name: jar-dirs
          mountPath: /usr/local/erp
        - name: zipkin-log
          mountPath: /var/log/zipkin
        command: ["java"]
        args: ["-Duser.timezone=GMT+08","-jar","/usr/local/erp/erp_logistics_engine.jar","--spring.profiles.active=prod"]
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1"
            ephemeral-storage: "1024Mi"
          limits:
            memory: "32Gi"
            cpu: "8"
            ephemeral-storage: "10240Mi"
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      - name: jar-dirs
        hostPath:
          path: /data/gfs_data
      - name: zipkin-log
        persistentVolumeClaim:
          claimName: zipkin-logistics-engine-pvc
---

# -----------------------  Service  --------------------- #
apiVersion: v1
kind: Service
metadata:
  name: logistics-engine-svc
spec:
  type: NodePort
  selector:
    app: logistics-engine
    release: proc
  ports:
  - name: api1
    protocol: TCP
    port: 80
    nodePort: 31021
    targetPort: 80 
