# -----------------------Deployment---------------------- #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-frontend
      release: proc
  template:
    metadata:
      labels:
        app: nginx-frontend
        release: proc
    spec:
      containers:
      - name: nginx
        image: c7nginx:v1
        resources:
          requests:
            memory: "2048Mi"
          limits:
            memory: "8192Mi"
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        - name: nginx-conf
          mountPath: /etc/nginx
        - name: data-erp-dir
          mountPath: /usr/local/erp
        - name: data-customer-dir
          mountPath: /usr/local/customer
        - name: data-logistics-dir
          mountPath: /usr/local/logistics_track
        - name: data-pms-web-dir
          mountPath: /usr/local/pms_web
        - name: data-logistics-engine-dir 
          mountPath: /usr/local/logistics-engine
        - name: data-sale-dir 
          mountPath: /usr/local/sale-service
        ports: 
        - containerPort: 80
        - containerPort: 81
        - containerPort: 82
        - containerPort: 83
        - containerPort: 84
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      - name: nginx-conf
        hostPath:
          path: /data/gfs_nginx_conf/
      - name: data-customer-dir
        hostPath:
          path: /data/gfs_nginx_customer/
      - name: data-erp-dir
        hostPath:
          path: /data/gfs_nginx_erp/
      - name: data-logistics-dir
        hostPath:
          path: /data/gfs_nginx_logistics_track/
      - name: data-pms-web-dir
        hostPath:
          path: /data/gfs_nginx_pms_web/
      - name: data-logistics-engine-dir
        hostPath:
          path: /data/gfs_nginx_logistics-engine/
      - name: data-sale-dir
        hostPath:
          path: /data/gfs_nginx_sale/
---

# -----------------------  Service    --------------------- #
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx-frontend
    release: proc
  ports:
  - name: nginx80
    protocol: TCP
    port: 80
    nodePort: 30080
    targetPort: 80
  - name: nginx81
    protocol: TCP
    port: 81
    nodePort: 30081
    targetPort: 81
  - name: nginx82
    protocol: TCP
    port: 82
    nodePort: 30082
    targetPort: 82
  - name: nginx83
    protocol: TCP
    port: 83
    nodePort: 30083
    targetPort: 83
  - name: nginx84
    protocol: TCP
    port: 84
    nodePort: 30084
    targetPort: 84

--- 
