# -----------------------Deployment---------------------- #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pms-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pms
      release: proc
  template:
    metadata:
      labels:
        app: pms
        release: proc
    spec:
      containers:
      - name: pms
        image: c7jdk8:v8 
        ports: 
        - containerPort: 80
        - containerPort: 9999
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1"
            ephemeral-storage: "1024Mi"
          limits:
            memory: "32Gi"
            cpu: "4"
            ephemeral-storage: "10240Mi"
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        - name: jar-dirs
          mountPath: /usr/local/erp
        - name: xxl-job
          mountPath: /var/log/xxl-job
        - name: zipkin-log
          mountPath: /var/log/zipkin
        command: ["java"]
        args: ["-Duser.timezone=GMT+08","-jar","/usr/local/erp/erp_pms.jar","--spring.profiles.active=prod"]
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      - name: jar-dirs
        hostPath:
          path: /data/gfs_data
      - name: xxl-job
        nfs:
          server: 192.168.1.252
          path: /nfs
      - name: zipkin-log
        persistentVolumeClaim:
          claimName: zipkin-pms-pvc
---

# -----------------------  Service  --------------------- #
apiVersion: v1
kind: Service
metadata:
  name: pms-svc
spec:
  type: NodePort
  selector:
    app: pms
    release: proc
  ports:
  - name: api1
    protocol: TCP
    port: 80
    nodePort: 31061
    targetPort: 80 
  - name: api2
    protocol: TCP
    port: 9999
    nodePort: 31999
    targetPort: 9999 
